### ISSUE TITLE
more support for request and response body functionality

### ISSUE THREAD

**Issue by talentedmrjones** [aquia-inc/emberfall#18]
Currently there is no ability to send body data in _requests_ which greatly limits usability in regards to api testing.

While there is basic functionality for matching the _response_ body, it is a strict equality kind of check. A more helpful check would be supporting either or both, regex or json field matching

The proposed design is as follows:

```yaml
tests:
  - url: string
    method: string # one valid HTTP request method
    body: object # the key of the object determines the kind of encoding the request uses
      json: # object, arbitrary key:value pairs sent as json
      text: # string sent as plain text
    expect:
      status: int # compared with response status
      headers: object # key:values compared with those from the response headers as strict equality
      body: object # the key of the object determines the encoding applied to the response
        json: # arbitary key:value pairs matched to the response
        text: # string applies as stricit equality
        regex: # string as Go formatted regex applied as Match
```
