### ISSUE TITLE
support more flexible assertions

### ISSUE THREAD

**Issue by talentedmrjones** [aquia-inc/emberfall#21]
Currently the `expect` API matches based on strict equality. I propose to replace `expect:` with `assert:` and provide functions such as `!eq`, `!gt`, `!lt`, `!regex` etc to each field as such:

```yaml
tests:
- url: string
  assert:
    status: !eq 200 # or !gt 200
    body:
      text: !regex "foo" # to find any match, or !regex "^foo" to starts with match
```
