### ISSUE TITLE
emberfall panics when expecting an array in body.json

### ISSUE THREAD

**Issue by talentedmrjones** [aquia-inc/emberfall#36]
A test like the following:
```yaml
- url: http://localhost:8080/api/v1/users
    method: GET
    headers:
      <<: *commonHeaders
    expect:
      status: 200
      headers:
        content-type: "application/json"
      body:
        json:
          data:
          - email: "test.user@nowhere.xyz"
            fullname: "Test User"
            role: "ADMIN"
            deleted: false
```

Will panic with the following error:
```
panic: runtime error: comparing uncomparable type []interface {}
```
